version: '3.8'

services:
  backend:
    build: ./backend
    container_name: language-platform-backend
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - backend-data:/app
    networks:
      - language-platform-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: "http://localhost:5001"
    container_name: language-platform-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - language-platform-network
    restart: unless-stopped

volumes:
  backend-data:
    driver: local

networks:
  language-platform-network:
    driver: bridge
